Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 152
Naming/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
